name: nutrilog
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

scripts:
  get: fvm flutter pub get

  clean:
    $script: fvm flutter clean
    $after: $get

  gen:
    $before: $clean
    $script: fvm flutter pub run build_runner watch --delete-conflicting-outputs

  test:
    $before: fvm flutter pub run full_coverage
    $script: fvm flutter test --coverage

dependencies:
  auto_size_text: ^3.0.0
  brasil_fields: ^1.14.0
  cloud_firestore: ^4.9.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  device_preview: 1.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_crashlytics: 3.3.4
  firebase_remote_config: 4.2.4
  flutter:
    sdk: flutter
  flutter_mobx: 2.0.6+5
  flutter_modular: 5.0.3
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.0+1
  fluttertoast: ^8.2.4
  fpdart: 0.4.1
  intl: ^0.18.0
  mobx: 2.2.0
  permission_handler: 10.4.3
  uuid: ^4.3.3

dev_dependencies:
  build_runner: 2.4.6
  flutter_flavorizr: 2.1.5
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  full_coverage: ^1.0.0
  mobx_codegen: 2.3.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icon/
    - assets/logo/
    - assets/icons/
    - assets/jsons/
    - assets/gifs/

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/K2D-Light.ttf
          weight: 300
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 400
        - asset: assets/fonts/K2D-Regular.ttf
          weight: 500
        - asset: assets/fonts/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/K2D-ExtraBold.ttf
          weight: 800

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/app_icon/app_icon_square.png"
  image_path_android: "assets/app_icon/app_icon_square.png"
  adaptive_icon_background: "assets/app_icon/app_icon_android_background.png"
  adaptive_icon_foreground: "assets/app_icon/app_icon_android_foreground.png"
  remove_alpha_ios: true

flavorizr:
  flavors:
    prod:
      app:
        name: "Nutrilog"

      android:
        applicationId: "com.nutrilog"
        firebase:
          config: "firebase/prod/google-services.json"
      ios:
        bundleId: "com.nutrilog"
        firebase:
          config: "firebase/prod/GoogleService-Info.plist"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"
          ASSET_PREFIX:
            value: ""
          TARGET_NAME:
            value: "Nutrilog"

    dev:
      app:
        name: "Nutrilog DEV"

      android:
        applicationId: "com.nutrilog.dev"
        firebase:
          config: "firebase/dev/google-services.json"
      ios:
        bundleId: "com.nutrilog.dev"
        firebase:
          config: "firebase/dev/GoogleService-Info.plist"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"
          ASSET_PREFIX:
            value: ""
          TARGET_NAME:
            value: "Nutrilog DEV"
